service: dgraphql-serverless

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  vpc:
    securityGroupIds:
      - Fn::GetAtt:
        - DgraphSecurityGroup
        - GroupId
    subnetIds:
      - subnet-fb848883
      - subnet-d13f139b

plugins:
  - serverless-webpack

functions:
  graphql:
    handler: handler.graphql
    environment:
      DGRAPH:
        Fn::GetAtt:
          - DgraphInstance
          - PrivateIp
    events:
      - http:
          path: /
          method: post
          cors: true
          integration: lambda-proxy
      - http:
          path: /
          method: get
          cors: true
          integration: lambda-proxy

resources:
  Mappings:
    RegionMap:
      us-east-2:
        "64": "ami-618fab04"
      us-east-1:
        "64": "ami-80861296"
      us-west-1:
        "64": "ami-2afbde4a"
      us-west-2:
        "64": "ami-efd0428f"
      ca-central-1:
        "64": "ami-b3d965d7"
      ap-south-1:
        "64": "ami-c2ee9dad"
      ap-northeast-2:
        "64": "ami-66e33108"
      ap-southeast-1:
        "64": "ami-8fcc75ec"
      ap-southeast-2:
        "64": "ami-96666ff5"
      ap-northeast-1:
        "64": "ami-afb09dc8"
      eu-central-1:
        "64": "ami-060cde69"
      eu-west-1:
        "64": "ami-a8d2d7ce"
      eu-west-2:
        "64": "ami-f1d7c395"
      sa-east-1:
        "64": "ami-4090f22c"
  Resources:
    DgraphSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Lock down Dgraph
    DgraphIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        GroupName:
          Ref: DgraphSecurityGroup
        IpProtocol: tcp
        ToPort: 8080
        FromPort: 8080
        SourceSecurityGroupName:
          Ref: DgraphSecurityGroup
    DgraphInstance:
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: t2.medium
        ImageId:
          Fn::FindInMap:
            - RegionMap
            - Ref: AWS::Region
            - 64
        SecurityGroups:
          - Ref: DgraphSecurityGroup
        UserData:
          Fn::Base64: |
            #!/bin/bash

            # install dgraph
            sudo apt-get update -y
            sudo apt-get install -y gcc
            curl https://get.dgraph.io -sSf | bash

            # create dgraph.service
            sudo bash -c 'cat << EOF > /etc/systemd/system/dgraph.service
            [Unit]
            Description=dgraph

            [Service]
            ExecStart=/usr/local/bin/dgraph -w /home/ubuntu/dgraph/w -p /home/ubuntu/dgraph/p -bindall
            Restart=always
            User=ubuntu

            [Install]
            WantedBy=multi-user.target
            EOF'

            # enable and start dgraph service
            sudo systemctl enable dgraph.service
            sudo systemctl start dgraph.service
